### PR TITLE
fix(no-global-setup): incorrectly triggered by describe.only

### LINKED ISSUE #145: beforeAll inside describe.only triggers no-global-setup
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```js

describe.only('suite', () => {

  beforeAll(() => { /* localsetup */ }); // 'Do not use `beforeAll` outside a `describe` except for in global helpers.

});
```

**What is the expected behavior?**

No warning.

### PR DESCRIPTION
**Pull request by DianaSuvorova**
fixes #145

### CODE REVIEW

File: lib/helpers/getName.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
+/*
+  getName(describe()) === 'describe';
+  getName(describe.only()) === 'describe.only';
+  getName(desctibe['only']()) === 'describe.only';
```
Comment (burabure) [inline lib/helpers/getName.js]: desc**t**ibe

Comment (DianaSuvorova) [reply lib/helpers/getName.js]: corrected
