### PR TITLE
fix(new-line-before-expect): ok if another expect on the prev line

### LINKED ISSUE #141: new-line-before-expect improvement
The following example I feel it should not trigger a `new-line-before-expect` warning:

```
it("should do something", function () {
  var a = 3;

  expect(a).toBeDefined();
  expect(a).toBe(3);
});
```

### PR DESCRIPTION
**Pull request by surdu**
Fixes #141

### CODE REVIEW

**Comment by surdu** [comment]
Ironically, you're not using eslint for this project 😆

File: lib/rules/new-line-before-expect.js [hunk 1]
```diff
@@ -8,14 +8,21 @@
 var hasPaddingBetweenTokens = require('../helpers/hasPaddingBetweenTokens')
 
 var blockRegexp = /^((f|x)?(it|describe))$/
+var lastExpectNode
```
Comment (DianaSuvorova) [inline lib/rules/new-line-before-expect.js]: Instead of declaring  it here and resetting inside CallExpression, can we declare it in the scope it will be used. So inside CallExpression?

**Comment by DianaSuvorova** [comment]
@surdu we are using standard which is in its turn using eslint. So we are using eslint 😉

File: lib/rules/new-line-before-expect.js (hunk 1 above)
Comment (surdu) [inline lib/rules/new-line-before-expect.js]: Good point...

**Comment by DianaSuvorova** [comment]
@surdu  Also please squash your change in one commit after this fix.

File: lib/rules/new-line-before-expect.js (hunk 1 above)
Comment (surdu) [inline lib/rules/new-line-before-expect.js]: Well, actually, it would not work, because it will reset every time, even when it will be called for the second expect node.

**Comment by surdu** [comment]
@DianaSuvorova I'm afraid I don't know how to squash my changes into one commit :(

File: lib/rules/new-line-before-expect.js (hunk 1 above)
Comment (DianaSuvorova) [inline lib/rules/new-line-before-expect.js]: I see, can we declare it on the same level as suiteDepth then? :)

Comment (surdu) [inline lib/rules/new-line-before-expect.js]: Sure thing

**Comment by DianaSuvorova** [comment]
@surdu on your branch: `git rebase -i master` it will ask you what commits to pick and to squash. It is interactive so git will walk you through the process . https://stackoverflow.com/questions/363908/how-do-i-use-git-rebase-i-to-rebase-all-changes-in-a-branch

After that do `git push -f origin improve-new-line-before-expect`


Since we have auto releaser set up here. Your commits will be a part of release notes. I want to make sure they make sense.


Let me know if you need help.

Diana

**Comment by surdu** [comment]
That was tense 😅

File: lib/rules/new-line-before-expect.js [hunk 2]
```diff
@@ -40,3 +47,13 @@ module.exports = function (context) {
     }
   }
 }
+
+/**
```
Comment (DianaSuvorova) [inline lib/rules/new-line-before-expect.js]: @surdu , There is one more thing to fix here:  This function annotation makes no sense. Either delete it all together or correct expected input and return types. 
And squash it after ...
Sorry I didn't catch it first time around

**Comment by surdu** [comment]
@DianaSuvorova done

**Comment by DianaSuvorova** [comment]
Looks great, Thanks @surdu !
